#pragma once

#include <unordered_map>
#include <SDL3/SDL.h>
#include <string>

inline const std::unordered_map<std::string, SDL_Scancode> keyMap = {
    {"A", SDL_SCANCODE_A}, {"B", SDL_SCANCODE_B}, {"C", SDL_SCANCODE_C}, {"D", SDL_SCANCODE_D},
    {"E", SDL_SCANCODE_E}, {"F", SDL_SCANCODE_F}, {"G", SDL_SCANCODE_G}, {"H", SDL_SCANCODE_H},
    {"I", SDL_SCANCODE_I}, {"J", SDL_SCANCODE_J}, {"K", SDL_SCANCODE_K}, {"L", SDL_SCANCODE_L},
    {"M", SDL_SCANCODE_M}, {"N", SDL_SCANCODE_N}, {"O", SDL_SCANCODE_O}, {"P", SDL_SCANCODE_P},
    {"Q", SDL_SCANCODE_Q}, {"R", SDL_SCANCODE_R}, {"S", SDL_SCANCODE_S}, {"T", SDL_SCANCODE_T},
    {"U", SDL_SCANCODE_U}, {"V", SDL_SCANCODE_V}, {"W", SDL_SCANCODE_W}, {"X", SDL_SCANCODE_X},
    {"Y", SDL_SCANCODE_Y}, {"Z", SDL_SCANCODE_Z},

    {"1", SDL_SCANCODE_1}, {"2", SDL_SCANCODE_2}, {"3", SDL_SCANCODE_3}, {"4", SDL_SCANCODE_4},
    {"5", SDL_SCANCODE_5}, {"6", SDL_SCANCODE_6}, {"7", SDL_SCANCODE_7}, {"8", SDL_SCANCODE_8},
    {"9", SDL_SCANCODE_9}, {"0", SDL_SCANCODE_0},

    {"F1", SDL_SCANCODE_F1}, {"F2", SDL_SCANCODE_F2}, {"F3", SDL_SCANCODE_F3}, {"F4", SDL_SCANCODE_F4},
    {"F5", SDL_SCANCODE_F5}, {"F6", SDL_SCANCODE_F6}, {"F7", SDL_SCANCODE_F7}, {"F8", SDL_SCANCODE_F8},
    {"F9", SDL_SCANCODE_F9}, {"F10", SDL_SCANCODE_F10}, {"F11", SDL_SCANCODE_F11}, {"F12", SDL_SCANCODE_F12},

    {"SPACE", SDL_SCANCODE_SPACE}, {"ENTER", SDL_SCANCODE_RETURN}, {"ESC", SDL_SCANCODE_ESCAPE},
    {"TAB", SDL_SCANCODE_TAB}, {"BACKSPACE", SDL_SCANCODE_BACKSPACE}, {"CAPSLOCK", SDL_SCANCODE_CAPSLOCK},

    {"LSHIFT", SDL_SCANCODE_LSHIFT}, {"RSHIFT", SDL_SCANCODE_RSHIFT}, {"LCTRL", SDL_SCANCODE_LCTRL},
    {"RCTRL", SDL_SCANCODE_RCTRL}, {"LALT", SDL_SCANCODE_LALT}, {"RALT", SDL_SCANCODE_RALT},
    {"LGUI", SDL_SCANCODE_LGUI}, {"RGUI", SDL_SCANCODE_RGUI},

    {"UP", SDL_SCANCODE_UP}, {"DOWN", SDL_SCANCODE_DOWN}, {"LEFT", SDL_SCANCODE_LEFT}, {"RIGHT", SDL_SCANCODE_RIGHT},

    {"NUMPAD_1", SDL_SCANCODE_KP_1}, {"NUMPAD_2", SDL_SCANCODE_KP_2}, {"NUMPAD_3", SDL_SCANCODE_KP_3},
    {"NUMPAD_4", SDL_SCANCODE_KP_4}, {"NUMPAD_5", SDL_SCANCODE_KP_5}, {"NUMPAD_6", SDL_SCANCODE_KP_6},
    {"NUMPAD_7", SDL_SCANCODE_KP_7}, {"NUMPAD_8", SDL_SCANCODE_KP_8}, {"NUMPAD_9", SDL_SCANCODE_KP_9},
    {"NUMPAD_0", SDL_SCANCODE_KP_0}, {"NUMPAD_ENTER", SDL_SCANCODE_KP_ENTER},
    {"NUMPAD_PLUS", SDL_SCANCODE_KP_PLUS}, {"NUMPAD_MINUS", SDL_SCANCODE_KP_MINUS},
    {"NUMPAD_MULTIPLY", SDL_SCANCODE_KP_MULTIPLY}, {"NUMPAD_DIVIDE", SDL_SCANCODE_KP_DIVIDE},
    {"NUMPAD_DECIMAL", SDL_SCANCODE_KP_DECIMAL},

    {"HOME", SDL_SCANCODE_HOME}, {"END", SDL_SCANCODE_END}, {"INSERT", SDL_SCANCODE_INSERT},
    {"DELETE", SDL_SCANCODE_DELETE}, {"PAGEUP", SDL_SCANCODE_PAGEUP}, {"PAGEDOWN", SDL_SCANCODE_PAGEDOWN},
    {"PRINTSCREEN", SDL_SCANCODE_PRINTSCREEN}, {"SCROLLLOCK", SDL_SCANCODE_SCROLLLOCK},
    {"PAUSE", SDL_SCANCODE_PAUSE}
};
